# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to execute our Python scripts and tests.
jobs:
  run-python-tests:
    docker:
      # Use CircleCI's Python image
      - image: cimg/python:3.12 # Update based on your Python version

    steps:
      - checkout # Checkout the repository code

      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt  # Ensure you have this file

      - run:
          name: Run GitHub API Script
          command: python github.py # Runs github.py script

      - run:
          name: Run Unit Tests
          command: python -m unittest discover # Runs all tests in testgithub.py

# Define workflows to orchestrate job execution
workflows:
  run-tests-workflow:
    jobs:
      - run-python-tests
