name: Run Python Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Pulls the latest repo code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # Adjust based on your local version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have this file listing dependencies

      - name: Run GitHub API Script
        run: python github.py # Runs github.py script

      - name: Run Tests
        run: python -m unittest discover # Runs all tests in testgithub.py
